[package]
name = "inspektor"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.13.0", features = ["full"] }
tokio-util = { version = "0.6.9", features = ["full"]}
byteorder = "1.4.3"
bytes = "1.1.0"
anyhow = "1.0"
thiserror = "1.0"
log = "0.4"
env_logger = "0.8.4"
tokio-native-tls = "0.3.0"

[env]
RUST_LOG="debug"

