version: '3.8'

services:
  postgres:
    container_name: postgres_systest_container
    image: postgres:13.5
    environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgrespass"
    ports:
     - 5432:5432
    restart: unless-stopped