driver_type: "postgres"
controlplane_addr: "localhost:5432"
secret_token: "control plane secret token"
postgres_config:
  target_addr: "postgres:2312"
  target_username: "postgres"
  target_password: "demopostgrespassword"
  proxy_listen_port: "1001"