name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.14.0'
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: 1.60.0-nightly
        override: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1'
    - name: "system testing"
      run : cd systest && chmod u+x ./test.sh; ./test.sh
