name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        version: '3.x'
        include-pre-releases: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
